spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: id
            clientSecret: secret

logging:
  level:
    rg.springframework.security: INFO